# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chris Isaacs
#email: me [at] this domain
description: >- 
  Hi there! I'm Chris Isaacs. I deliver software for a living 

  in a bunch of different domains. I enjoy working with people  

  and solving business problems using technology. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chrisaacs.com"
twitter_username:   OdiousCode
github_username:    chsscs
linkedin_username:  chrisaacs

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
