name: Pipeline
on:
  workflow_call:
    inputs:
      refs:
        required: true
        type: string
      environmnet:
        required: true
        type: string
      site-prefix:
        required: true
        type: string
      code-directory:
        required: true
        type: string
jobs:
  code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmnet }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.code-directory }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.refs }}
    - name: build
      run: |
          echo "build: ${{ inputs.environmnet }}"
          echo "deploy: ${{ inputs.site-prefix }}"
