name: Pipeline
on:
  workflow_call:
    inputs:
      refs:
        required: true
        type: string
      environmnet:
        required: true
        type: string
      site-prefix:
        required: true
        type: string
      code-directory:
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "single"

jobs:
  code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmnet }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.code-directory }}
    steps:
    - name: build
      run: |
          echo "build: ${{ inputs.environmnet }}"
          echo "deploy: ${{ inputs.site-prefix }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.refs }}
      - name: pages
        uses: actions/configure-pages@v5
      - name: build
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: upload
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4